#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo Must specify a valid version of cmake eg. cvm 3.19.7
	exit 1
fi

platform='unknown'
unamestr=$(uname)

if [ "$unamestr" == 'Linux' ]; then
	platform='Linux'

elif [ "$unamestr" == 'Darwin' ]; then
	platform='Darwin'

	if ! brew ls --versions jq >/dev/null; then
		echo Please install the jq library: \`brew install jq\`
		exit 1
	fi
fi

if [ "$platform" == 'unknown' ]; then
	echo "Currently only Linux and Darwin platforms are supported"
	exit 1
fi

if [ $1 == 'list' ]; then
	echo Available Versions:

	echo $(curl -s https://raw.githubusercontent.com/ChrisZiraldo/cvm/master/versions.json | jq -r '.'\"$platform\"'[] | .version') | tr " " "\n"

	exit 0
fi

version=$1
url=$(curl -s https://raw.githubusercontent.com/ChrisZiraldo/cvm/master/versions.json | jq -r '.'\"$platform\"'[] | select(.version=='\"$version\"') | .url')

if [ -z "$url" ]; then
	echo Version not defined in "https://raw.githubusercontent.com/ChrisZiraldo/cvm/master/versions.json"
	exit 1
fi

folder_name=cmake-${version}
file_name=${folder_name}.tar.gz
cvm_home=${HOME}/.cvm

if [ ! -d "${cvm_home}/${folder_name}" ]; then
	echo downloading cmake version ${version}
	echo from: ${url}
	echo to: ${cvm_home}/${file_name}
	pushd ${cvm_home} >/dev/null
	curl -L -o ${file_name} ${url}
	tar zxf ${file_name}
	tar_return_code=$?
	mv $(tar -tf ${file_name} | head -n1 | cut -d "/" -f1) ${folder_name} && rm ${file_name}
	popd >/dev/null

	if [ $tar_return_code != 0 ]; then
		echo "Error happened when extracting archive, exiting..."
		exit $?
	fi

fi

if [ "${platform}" = "Darwin" ]; then
	rm -r ${cvm_home}/"cmake-active"/CMake.app 2>/dev/null
	pushd ${cvm_home}/"cmake-active" >/dev/null
	ln -s ${cvm_home}/${folder_name}/CMake.app CMake.app
	popd >/dev/null

	cmake_bin=${cvm_home}/"cmake-active"/CMake.app/Contents/bin/
else
	rm -r ${cvm_home}/"cmake-active"/bin 2>/dev/null
	rm -r ${cvm_home}/"cmake-active"/share 2>/dev/null
	rm -r ${cvm_home}/"cmake-active"/man 2>/dev/null
	pushd ${cvm_home}/"cmake-active" >/dev/null
	ln -s ${cvm_home}/${folder_name}/bin bin
	ln -s ${cvm_home}/${folder_name}/share share
	ln -s ${cvm_home}/${folder_name}/man man
	popd >/dev/null

	cmake_bin=${cvm_home}/"cmake-active"/bin/
fi

echo -n "Active "
version=$(cmake --version)
echo ${version%$'\n'*}
